### ISSUE TITLE
Bugs & More Comprehensive Unit Tests Needed

### ISSUE THREAD

**Issue by SE2Dev** [elbeno/semver#2]
I've noticed that even though all unit tests appear to pass, certain functions aren't always necessarily correct.

I wrote the following program to test the library:
```cpp
#include <stdio.h>
#include "semantic_version.h"

typedef semver::v2::Version Version_t;

void PrintVersion(Version_t version)
{
	printf("Is Well Formed: %s\n", version.IsWellFormed() ? "yes" : "no");
	printf("Major Version: %u\n", version.GetMajorVersion());
	printf("Minor Version: %u\n", version.GetMinorVersion());
	printf("Patch Version: %u\n", version.GetPatchVersion());
	printf("\n");
}

int main(int argc, const char **argv)
{
	if (argc < 2 || argc > 3)
	{
		printf("Usage: a.out version [version]\n");
		return 1;
	}

	printf("Parsing version string: '%s'\n", argv[1]);
	Version_t version_a(argv[1]);
	PrintVersion(version_a);

	if (argc == 2)
	{
		printf("Printing next major version\n");
		PrintVersion(version_a.NextMajorVersion());

		printf("Printing next minor version\n");
		PrintVersion(version_a.NextMinorVersion());

		printf("Printing next patch version\n");
		PrintVersion(version_a.NextPatchVersion());
	}
	else
	{
		printf("Parsing version string: '%s'\n", argv[2]);
		Version_t version_b(argv[2]);
		PrintVersion(version_b);

		printf("A < B: %s\n", version_a < version_b ? "yes" : "no");
		printf("A == B: %s\n", version_a == version_b ? "yes" : "no");
		printf("A satisfies B: %s\n", version_a.Satisfies(version_b) ? "yes" : "no");
	}

	return 0;
}
```

Launching this program with the arguments: `1.2.3 4.5.6` yields the expected results, however if you launch the program with the arguments `4.5.6 1.2.3` the results appear to be incorrect: 
```
Parsing version string: '4.5.6'
Is Well Formed: yes
Major Version: 4
Minor Version: 5
Patch Version: 6

Parsing version string: '1.2.3'
Is Well Formed: yes
Major Version: 1
Minor Version: 2
Patch Version: 3

A < B: yes
A == B: no
A satisfies B: yes
```

Also it's worth noting that when running the above program (with the same arguments), using semver::v1 instead of semver::v2 the following results are produced:

```
Parsing version string: '4.5.6'
Is Well Formed: yes
Major Version: 4
Minor Version: 5
Patch Version: 6

Parsing version string: '1.2.3'
Is Well Formed: yes
Major Version: 1
Minor Version: 2
Patch Version: 3

A < B: no
A == B: no
A satisfies B: yes
```

It would appear that for both v1 and v2, the Satisfies() method appears to be broken, and for v2 the < operator appears to be broken.

**Comment by elbeno** [comment]
Fixed operator<  - https://github.com/elbeno/semver/commit/aa149fe5b956b9fb9dfa70cad048fd822f2b9c35

Satisfies() is correct, 4.5.6 does satisfy 1.2.3 because it's greater.

**Comment by SE2Dev** [comment]
> Satisfies() is correct, 4.5.6 does satisfy 1.2.3 because it's greater.
Yeah, I didn't quite realize that functionality described the terms "satisfy" and "satisfies" aren't explicitly defined in the specification, and instead was comparing the functionality to [node-semver](https://github.com/npm/node-semver).
