### ISSUE TITLE
Bug: v2 operator< uses <= for the prerelease version

### ISSUE THREAD

**Issue by hneubauer** [elbeno/semver#3]
Actually version 1.2.3 equals 1.2.3 because the operator < of v2 uses <= considering the pre release version (line 239 in semantiv_version_v2.cpp). There should be a < instead of <=.

**Comment by elbeno** [comment]
Fixed: https://github.com/elbeno/semver/commit/732098a5a3a9d7df01127cb80db5d03398e58f54
